name: CI - Test and Build

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev, stage]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Test Frontend
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      # Test Backend
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install backend dependencies
        run: |
          cd backend
          composer install

      - name: Test backend
        run: |
          cd backend
          php artisan --version
