name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, dev]


jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup PHP for Backend
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      
      # # Install Composer dependencies
      # - name: Install Composer dependencies
      #   run: composer install --prefer-dist --no-progress --no-suggest --no-interaction
        
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

     # Docker Build
      - name: Build Docker Containers
        run: docker-compose -f ./docker-compose.yml build

