name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup PHP for Backend
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      
      # Set up Node.js for Frontend
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      # Install frontend dependencies
      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm ci

      # Docker Build
      - name: Build Docker Containers
        run: docker-compose -f ./docker-compose.yml build
